resource "random_pet" "pet" {
    prefix    = var.prefix     # prepended to the pet name
    separator = var.separator  # character between prefix and name
    length    = var.length     # number of random words in the name
}

resource "local_file" "my-pet" {
    filename = var.filename
    content  = "My favourite pet is ${random_pet.pet.id}"
    # depends_on = [ random_pet.my-pet ] # explicit dependency
}
# terraform output pet-name or any variables which is saved as output.
# terraform output command
output "pet-name" {
  value = random_pet.pet.id
  description = "Records the value of Pet ID generated by the random_pet resource"
}